import { Inter } from "next/font/google";
import "./globals.css";
import { FunctionalityProvider } from "@/FunctionalilyContext";
import { SimulationProgressProvider } from "@/Contexts/SimulationProgressContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SimulationProgressProvider>
       <FunctionalityProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
   </FunctionalityProvider>
     </SimulationProgressProvider>
   
  );
}
